// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;

public enum ECameraPositions
{
	TopDown = 1,
	SideOn = 2,
	TV = 3,
	Chase = 4,
	Infront = 5,
}

